#数据库配置
spring:
  #数据源
  datasource:
    url: jdbc:mysql://192.168.1.10:3306/sports_online?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: group1
    password: group1
    driver-class-name: com.mysql.cj.jdbc.Driver
  #模板引擎配置
  thymeleaf:
    encoding: UTF-8
    #suffix: .html  默认后缀
    #prefix: classpath:/templates/  默认前缀

mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.znsd.sportsmallweb.getType.entity